"""
tools/mcp_builder.py — MCP Server Builder + Prompt Engineer  (v4.1)

Dua hal (sk24):
1. scaffold_mcp() — generate skeleton MCP server (Python FastMCP / TS sdk) dengan
   best practices (deskripsi tool tajam, schema ketat, error-as-data).
2. audit_prompt() — deteksi masalah prompt umum (heuristik, keyless).

MCP server = kode yang jalan → review sebelum expose; HTTP mode wajib auth.
Stdlib only. Pakai:
    from mcp_builder import scaffold_mcp, audit_prompt
    scaffold_mcp("weather", lang="python", tools=[{"name":"get_forecast","desc":"...","params":{"city":"str"}}])
    print(audit_prompt(system_prompt))
"""
from __future__ import annotations

import re
from pathlib import Path

PY_TEMPLATE = '''\
"""{name} MCP server — generated by mcp_builder (review before exposing)."""
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("{name}")

{tools}

if __name__ == "__main__":
    mcp.run()   # stdio default. Untuk remote: mcp.run(transport="streamable-http") + AUTH.
'''

PY_TOOL = '''\
@mcp.tool()
def {fn}({sig}) -> str:
    """{desc}"""   # deskripsi = cara host milih tool. Satu kalimat what+when.
    # TODO: implement. Return string/JSON yang LLM bisa pahami.
    # Error → return pesan jelas (error-as-data), JANGAN raise mentah.
    raise NotImplementedError("{fn}")
'''

TS_TEMPLATE = '''\
// {name} MCP server — generated by mcp_builder (review before exposing).
import {{ McpServer }} from "@modelcontextprotocol/sdk/server/mcp.js";
import {{ StdioServerTransport }} from "@modelcontextprotocol/sdk/server/stdio.js";
import {{ z }} from "zod";

const server = new McpServer({{ name: "{name}", version: "0.1.0" }});

{tools}

const transport = new StdioServerTransport();
await server.connect(transport);
'''

TS_TOOL = '''\
server.tool("{fn}", "{desc}", {{ {zsig} }}, async ({{ {args} }}) => {{
  // TODO: implement. return {{ content: [{{ type: "text", text: "..." }}] }};
  throw new Error("{fn} not implemented");
}});
'''

_PY_TYPES = {"str": "str", "int": "int", "float": "float", "bool": "bool"}
_Z_TYPES = {"str": "z.string()", "int": "z.number().int()", "float": "z.number()", "bool": "z.boolean()"}


def scaffold_mcp(name: str, lang: str = "python", tools=None, out_dir: str = None) -> str:
    """Generate MCP server skeleton. Return path folder."""
    tools = tools or []
    safe = re.sub(r"[^a-zA-Z0-9_-]", "-", name)
    dest = Path(out_dir or f"./mcp-{safe}")
    dest.mkdir(parents=True, exist_ok=True)

    if lang == "python":
        blocks = []
        for t in tools:
            params = t.get("params", {})
            sig = ", ".join(f"{p}: {_PY_TYPES.get(ty, 'str')}" for p, ty in params.items())
            blocks.append(PY_TOOL.format(fn=t["name"], sig=sig, desc=t.get("desc", t["name"])))
        (dest / "server.py").write_text(PY_TEMPLATE.format(name=name, tools="\n\n".join(blocks)))
        (dest / "pyproject.toml").write_text(
            f'[project]\nname = "mcp-{safe}"\nversion = "0.1.0"\ndependencies = ["mcp"]\n')
        run = "pip install mcp && python server.py"
    elif lang in ("ts", "typescript"):
        blocks = []
        for t in tools:
            params = t.get("params", {})
            zsig = ", ".join(f"{p}: {_Z_TYPES.get(ty, 'z.string()')}" for p, ty in params.items())
            args = ", ".join(params.keys())
            blocks.append(TS_TOOL.format(fn=t["name"], desc=t.get("desc", t["name"]), zsig=zsig, args=args))
        (dest / "server.ts").write_text(TS_TEMPLATE.format(name=name, tools="\n\n".join(blocks)))
        (dest / "package.json").write_text(
            '{\n  "name": "mcp-%s",\n  "type": "module",\n'
            '  "dependencies": {"@modelcontextprotocol/sdk": "^1.0.0", "zod": "^3.23.0"}\n}\n' % safe)
        run = "npm install && npx tsx server.ts"
    else:
        raise ValueError(f"lang harus python|ts, dapet {lang}")

    (dest / "README.md").write_text(
        f"# mcp-{safe}\n\nGenerated MCP server. **Review sebelum expose.**\n\n"
        f"Run:\n```\n{run}\n```\n\nTools: {[t['name'] for t in tools]}\n"
        "Best practice: deskripsi tool tajam, schema ketat, error-as-data, HTTP→auth.\n")
    return str(dest)


# ───────────────── prompt engineer ─────────────────
_PROMPT_CHECKS = [
    (lambda p: not re.search(r"(format|json|markdown|skema|struktur|bullet|tabel)", p, re.I),
     "no-output-format", "tentukan format/skema output yang diharapkan"),
    (lambda p: len(re.findall(r"\b(jangan|don'?t|never|hindari|avoid)\b", p, re.I)) >= 3
     and not re.search(r"\b(lakukan|harus|do|always|return|output)\b", p, re.I),
     "negation-only", "kasih instruksi POSITIF (yang HARUS dilakukan), bukan cuma larangan"),
    (lambda p: not re.search(r"(contoh|example|misal|e\.g\.|for instance)", p, re.I),
     "no-examples", "tambah 1-2 contoh (terutama edge case)"),
    (lambda p: len(p) > 1500 and len(re.findall(r"\n\s*\d+\.|\n\s*-", p)) < 3,
     "wall-of-text", "pecah jadi langkah/bagian bernomor"),
    (lambda p: len(re.findall(r"\b(dan juga|serta|lalu|kemudian|also|then)\b", p, re.I)) >= 6,
     "task-overload", "satu prompt kebanyakan tugas — pecah / chain"),
    (lambda p: bool(re.search(r"\b(mungkin|sebaiknya|kalau bisa|maybe|try to|if possible)\b", p, re.I)),
     "vague-modal", "ganti 'mungkin/kalau bisa' dengan instruksi tegas"),
]


def audit_prompt(prompt: str) -> dict:
    """Deteksi masalah prompt umum. Return {findings:[...], suggestions:[...]}."""
    findings, suggestions = [], []
    for check, label, fix in _PROMPT_CHECKS:
        try:
            if check(prompt):
                findings.append(label)
                suggestions.append(f"{label} → {fix}")
        except Exception:                       # noqa: BLE001
            continue
    return {"findings": findings, "suggestions": suggestions,
            "verdict": "OK" if not findings else f"{len(findings)} isu — perbaiki lalu eval (sk56)"}


if __name__ == "__main__":
    path = scaffold_mcp("demo", lang="python",
                        tools=[{"name": "ping", "desc": "Cek koneksi", "params": {"host": "str"}}],
                        out_dir="/tmp/_mcp_demo")
    print("scaffold →", path)
    print(audit_prompt("Jangan pakai jargon. Jangan terlalu panjang. Jangan formal."))
